import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
;<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css ,//cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
/>

import { Genos } from 'next/font/google'
import Header from '@/components/Header'
import './globals.css'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

const geist = Genos({
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={geist.className}>
        <body className="bg-gray-100">
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
